version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=tiago
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tiago
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - '27017:27017'   
